[2024-06-11T21:33:30.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:33:30.108+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704498 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:30.125+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704498 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:30.126+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:33:30.156+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_704498> on 2024-06-11 21:33:17.294204+00:00
[2024-06-11T21:33:30.169+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=540) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:33:30.168+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_704498', 'manual__2024-06-11T21:33:17.294204+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp4hckp8uy']
[2024-06-11T21:33:30.172+0000] {standard_task_runner.py:63} INFO - Started process 541 to run task
[2024-06-11T21:33:30.173+0000] {standard_task_runner.py:91} INFO - Job 216: Subtask load_index_id_704498
[2024-06-11T21:33:30.306+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_704498 manual__2024-06-11T21:33:17.294204+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:33:30.556+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_704498' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:33:17.294204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:33:17.294204+00:00'
[2024-06-11T21:33:30.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:33:30.664+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:33:30.668+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:33:30.670+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:33:30.702+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_704498, execution_date=20240611T213317, start_date=20240611T213330, end_date=20240611T213330
[2024-06-11T21:33:30.738+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 216 for task load_index_id_704498 (Task failed due to SystemExit(1); 541)
[2024-06-11T21:33:30.753+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:33:30.786+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:33:30.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
