[2024-04-28T05:19:24.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T05:19:24.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T05:19:24.358+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T05:19:24.359+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T05:19:24.379+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_2979005> on 2024-04-27 22:35:33.025533+00:00
[2024-04-28T05:19:24.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_2979005', 'manual__2024-04-27T22:35:33.025533+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp9ai483h_']
[2024-04-28T05:19:24.395+0000] {standard_task_runner.py:91} INFO - Job 256: Subtask load_index_id_2979005
[2024-04-28T05:19:24.396+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=14079) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-28T05:19:24.397+0000] {standard_task_runner.py:63} INFO - Started process 14080 to run task
[2024-04-28T05:19:24.465+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T22:35:33.025533+00:00 [running]> on host d933ead87eb5
[2024-04-28T05:19:24.585+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_2979005' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T22:35:33.025533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T22:35:33.025533+00:00'
[2024-04-28T05:19:24.587+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T05:19:31.510+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-04-28T05:19:31.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T05:19:31.512+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-04-28T05:19:31.524+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_2979005, execution_date=20240427T223533, start_date=20240428T051924, end_date=20240428T051931
[2024-04-28T05:19:31.544+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 256 for task load_index_id_2979005 (Task failed due to SystemExit(1); 14080)
[2024-04-28T05:19:31.582+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T05:19:31.603+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T05:19:31.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
