[2024-04-28T12:24:00.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T12:24:00.184+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701276 manual__2024-04-28T12:23:57.508175+00:00 [queued]>
[2024-04-28T12:24:00.254+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701276 manual__2024-04-28T12:23:57.508175+00:00 [queued]>
[2024-04-28T12:24:00.258+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T12:24:00.471+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701276> on 2024-04-28 12:23:57.508175+00:00
[2024-04-28T12:24:00.500+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701276', 'manual__2024-04-28T12:23:57.508175+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp86tot5no']
[2024-04-28T12:24:00.510+0000] {standard_task_runner.py:91} INFO - Job 305: Subtask load_index_id_701276
[2024-04-28T12:24:00.540+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=23557) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-28T12:24:00.542+0000] {standard_task_runner.py:63} INFO - Started process 23558 to run task
[2024-04-28T12:24:00.636+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701276 manual__2024-04-28T12:23:57.508175+00:00 [running]> on host d933ead87eb5
[2024-04-28T12:24:00.775+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701276' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T12:23:57.508175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T12:23:57.508175+00:00'
[2024-04-28T12:24:00.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T12:24:21.790+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T12:24:21.792+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_mb.py", line 26, in load_index
    for status in response.json()["info"]:
                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[2024-04-28T12:24:21.818+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701276, execution_date=20240428T122357, start_date=20240428T122400, end_date=20240428T122421
[2024-04-28T12:24:21.865+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 305 for task load_index_id_701276 ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(load_data_mb, load_index_id_701276, manual__2024-04-28T12:23:57.508175+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'load_index_id_701276', 'dag_id': 'load_data_mb', 'run_id': 'manual__2024-04-28T12:23:57.508175+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 28, 12, 24, 0, 191906, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 28, 12, 24, 21, 817119, tzinfo=Timezone('UTC')), 'duration': 21}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 23558)
[2024-04-28T12:24:21.890+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T12:24:21.907+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
