[2024-06-11T21:46:05.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:46:05.178+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:46:05.195+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:46:05.197+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:46:05.220+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703039> on 2024-06-11 21:41:03.459046+00:00
[2024-06-11T21:46:05.228+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:46:05.231+0000] {standard_task_runner.py:63} INFO - Started process 279 to run task
[2024-06-11T21:46:05.228+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703039', 'manual__2024-06-11T21:41:03.459046+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmphz8csiqq']
[2024-06-11T21:46:05.233+0000] {standard_task_runner.py:91} INFO - Job 296: Subtask load_index_id_703039
[2024-06-11T21:46:05.302+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:41:03.459046+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:46:05.675+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703039' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:41:03.459046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:41:03.459046+00:00'
[2024-06-11T21:46:05.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:46:05.879+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:46:05.887+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:46:05.889+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:46:05.944+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703039, execution_date=20240611T214103, start_date=20240611T214605, end_date=20240611T214605
[2024-06-11T21:46:06.050+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 296 for task load_index_id_703039 (Task failed due to SystemExit(1); 279)
[2024-06-11T21:46:06.133+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:46:06.195+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:46:06.201+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
