[2024-06-11T21:45:50.587+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:45:50.878+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701830 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:45:50.921+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701830 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:45:50.941+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:45:51.096+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701830> on 2024-06-11 21:41:03.459046+00:00
[2024-06-11T21:45:51.163+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:45:51.173+0000] {standard_task_runner.py:63} INFO - Started process 262 to run task
[2024-06-11T21:45:51.161+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701830', 'manual__2024-06-11T21:41:03.459046+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmppf6qfccv']
[2024-06-11T21:45:51.174+0000] {standard_task_runner.py:91} INFO - Job 293: Subtask load_index_id_701830
[2024-06-11T21:45:51.840+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701830 manual__2024-06-11T21:41:03.459046+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:45:52.354+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701830' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:41:03.459046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:41:03.459046+00:00'
[2024-06-11T21:45:52.356+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:45:53.513+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:45:53.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:45:53.529+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:45:53.690+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701830, execution_date=20240611T214103, start_date=20240611T214550, end_date=20240611T214553
[2024-06-11T21:45:53.739+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 293 for task load_index_id_701830 (Task failed due to SystemExit(1); 262)
[2024-06-11T21:45:53.819+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:45:53.853+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:45:53.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
